[package]
name = "raw_format_ansi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]
name = "raw_format_ansi"

[dependencies]
ansi-parser = "0.9.1"
regex = "1.11.1"

[dev-dependencies]
crossterm = { workspace = true }
captured_write = { path = "../captured_write" }
