[package]
name = "merchant"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
crossterm = "0.26.1"
rand = "0.8.5"
captured_write = { path ="../captured_write" }
raw_format_ansi = { path ="../raw_format_ansi" }

[dev-dependencies]
pretty_assertions = "1.4.0"
