[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.1"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["npm", "homebrew", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# A GitHub repo to push Homebrew formulas to
tap = "samgqroberts/homebrew-tap"
# The npm package should have this name
npm-package = "merchant-game"
# Publish jobs to run in CI
publish-jobs = ["homebrew", "npm"]
