name: build
run-name: Build Executables
on: [push]

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Ubuntu-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: merchant
          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: merchant
          - release_for: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: merchant
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get current rust app version from Cargo.toml.
        id: gameversion
        uses: SebRollen/toml-action@v1.2.0
        with:
          file: 'game/Cargo.toml'
          field: 'package.version'
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build binary
        run: cargo build --release
      - name: Create tarball
        id: tarball
        env:
          TARBALLNAME: ${{ format('merchant-{0}-{1}.tar.gz', steps.gameversion.outputs.value, matrix.platform.target) }}
        run: |
          cd target/release
          tar -czf $TARBALLNAME merchant
          echo "tarballname=$TARBALLNAME" >> $GITHUB_OUTPUT
          echo "shasum: $(shasum $TARBALLNAME | head -n1 | awk '{print $1;}')" >> $GITHUB_STEP_SUMMARY
      - uses: actions/upload-artifact@v4
        with:
            name: ${{ steps.tarball.outputs.tarballname }}
            path: target/release/merchant-*.tar.gz
            if-no-files-found: warn