name: build
run-name: Build Executables
on: [push]

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Ubuntu-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: merchant
            name: merchant-Ubuntu-x86_64.tar.gz
          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: merchant.exe
            name: merchant-Windows-x86_64.zip
          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: merchant
            name: merchant-Darwin-x86_64.tar.gz
          - release_for: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: merchant
            name: merchant-Darwin-aarch64.tar.gz
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build binary
        run: cargo build --release